app:
  datasource:
    main:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:55000/springjdbc
      username: postgres
      password: postgrespw
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always